export const COVID_TEST_REQUEST =" COVID_TEST_REQUEST";
export const COVID_TEST_SUCCESS ="COVID_TEST_SUCCESS";
export const COVID_TEST_FAILURE = "COVID_TEST_FAILURE";

export const STATEWISE_TESTCASES_REQUEST =" STATEWISE_TESTCASES_REQUEST";
export const STATEWISE_TESTCASES_SUCCESS =" STATEWISE_TESTCASES_SUCCESS";
export const STATEWISE_TESTCASES_FAILURE = " STATEWISE_TESTCASES_FAILURE";

